# install and run are the same commands
before_install:
  - python --version
install:
  - python -m pip install -U pip  # fixes dependency versioning issues 
  - pip install .[test]
  - pip install pytest-cov
script: python -m pytest ./tests --cov=endaq
after_success:
  - codecov

matrix:
  include:
    # Windows doesn't support native python yet, so here we are - 3.7
    - os: windows
      language: shell
      env: PATH=/c/python37:/c/Python37/scripts:$PATH
      before_install:
        - choco install python3 --version=3.7.9
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
    # Windows doesn't support native python yet, so here we are - 3.8
    - os: windows
      language: shell
      env: PATH=/c/python38:/c/Python38/scripts:$PATH
      before_install:
        - choco install python3 --version=3.8.8
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
    # Windows doesn't support native python yet, so here we are - 3.9
    - os: windows
      language: shell
      env: PATH=/c/python39:/c/Python39/scripts:$PATH
      before_install:
        - choco install python3 --version=3.9.2
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
  allow_failures:
    - if: env(ALLOW_FAILURES)=TRUE

# Linux is so much more cooperative
os: linux
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
