name: Unit test on push and PR


on: [push, pull_request, workflow_dispatch]


jobs:
  unit-tests:
    name: Run Docs Tests

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    env:
      OS: ${{ matrix.os }}
      PYTHON-VERSION: ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip

      - uses: actions/checkout@v2

      - run: python -m pip install .[docs]

      - run: sphinx-build -b html -W docs docs-html

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON-VERSION
          files: .coverage
          name: ${{ matrix.os }} ${{ matrix.python-version }}
          verbose: true
